set serveroutput on;
begin
DBMS_OUTPUT.PUT_LINE('DMDD Project');
end;

CREATE TABLE LOCATION 
(
  LOC_ID NUMBER PRIMARY KEY
, LOC_NAME VARCHAR2(20) 
);

CREATE TABLE BOOKINGS 
(
  BOOKING_ID NUMBER PRIMARY KEY
, FM_ID NUMBER 
, SLOT_ID NUMBER 
, BOOKING_TIME TIMESTAMP 
, BOOK_STATUS VARCHAR2(30) 
);

CREATE TABLE SLOTS
(
  SLOT_ID NUMBER PRIMARY KEY
, DAY_OF_WEEK VARCHAR2(20)
, SLOT_TIME TIMESTAMP
, SUBLOC_ID NUMBER
, SLOT_COUNT NUMBER
);

CREATE TABLE LOC_STATS 
(
  LOC_ID NUMBER 
, CURRENT_DATE DATE 
, IS_INSECT_SEINED VARCHAR2(1) 
, WATER_TEMP DECIMAL 
, LAST_DECON_TIME TIMESTAMP 
, O2_CONC_LEVEL DECIMAL 
, NH4_CONC_LEVEL DECIMAL 
, LAST_FEED_DATE TIMESTAMP 
);

ALTER TABLE BOOKINGS
ADD FOREIGN KEY (fm_id) REFERENCES fisherman(fm_id);
ALTER TABLE BOOKINGS
ADD FOREIGN KEY (slot_id) REFERENCES slots(slot_id);