set serveroutput on;
begin
DBMS_OUTPUT.PUT_LINE('DMDD Project');
end;
--Saivignesh Start
CREATE TABLE LOCATION 
(
  LOC_ID NUMBER PRIMARY KEY
, LOC_NAME VARCHAR2(20) 
);

CREATE TABLE BOOKINGS 
(
  BOOKING_ID NUMBER PRIMARY KEY
, FM_ID NUMBER 
, SLOT_ID NUMBER 
, BOOKING_TIME TIMESTAMP 
, BOOK_STATUS VARCHAR2(30) 
);

CREATE TABLE SLOTS
(
  SLOT_ID NUMBER PRIMARY KEY
, DAY_OF_WEEK VARCHAR2(20)
, SLOT_TIME TIMESTAMP
, SLOT_COUNT NUMBER
);

CREATE TABLE LOC_STATS 
(
  LOC_ID NUMBER 
, CURRENT_DATE DATE 
, IS_INSECT_SEINED VARCHAR2(1) 
, WATER_TEMP DECIMAL 
, LAST_DECON_TIME TIMESTAMP 
, O2_CONC_LEVEL DECIMAL 
, NH4_CONC_LEVEL DECIMAL 
, LAST_FEED_DATE TIMESTAMP 
);

ALTER TABLE BOOKINGS
ADD FOREIGN KEY (fm_id) REFERENCES fisherman(fm_id);
ALTER TABLE BOOKINGS
ADD FOREIGN KEY (slot_id) REFERENCES slots(slot_id);
-- Saivignesh Ends
-- Vignesh Start
drop table fisherman_details;
select * from fisherman_details;
Insert into fish_species values(514,'Yellow Perch',112,20);
--Vignesh End
----VISHAL START

CREATE TABLE CHECKIN_LOG 
(
  BOOKING_ID NUMBER 
, CHECKIN_ID NUMBER PRIMARY KEY 
, ENTRY_TIME TIMESTAMP
, COVID_RESULT VARCHAR(1)
, IS_PPE_AVAILABLE VARCHAR(1)
);

CREATE TABLE CHECKOUT_LOG 
(
  CHECKIN_ID NUMBER 
, FISH_INV_ID NUMBER
, CATCH_QTY NUMBER
, EXIT_TIME TIMESTAMP
);

CREATE TABLE SUB_LOCATION
(
  SUBLOC_ID NUMBER PRIMARY KEY
, SUBLOC_NAME VARCHAR(30)
, LOC_ID NUMBER
);
--- VISHAL END
--VISHAL START

ALTER TABLE CHECKIN_LOG
ADD FOREIGN KEY (booking_id) REFERENCES bookings(booking_id);

ALTER TABLE CHECKOUT_LOG
ADD FOREIGN KEY (checkin_id) REFERENCES checkin_log(checkin_id);







