SET SERVEROUTPUT ON;

DECLARE
ROW_CT NUMBER(10);
BEGIN 
    SELECT count(*) into ROW_CT FROM user_tables where table_name = 'FISHERMAN';
    IF(ROW_CT > 0)
    THEN
        DBMS_OUTPUT.PUT_LINE('TABLE CONFIG_TABLE ALREADY EXISTS');
    ELSE
        EXECUTE IMMEDIATE 'CREATE TABLE CONFIG_TABLE
     (	"FM_ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"AGE" NUMBER(*,0), 
	"GENDER" VARCHAR2(1 BYTE), 
	"EXPERIENCE" FLOAT(126), 
	"MOBILE_NO" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE)
   )
    ';    
     DBMS_OUTPUT.PUT_LINE('TABLE CONFIG_TABLE CREATED SUCCESSFULLY');
     END IF;
END;
/